
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiufgzoknpwgrtlnzvml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppdWZnem9rbnB3Z3J0bG56dm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTA3OTMsImV4cCI6MjA1OTA4Njc5M30.RWp0AyydNkzkHcmmn2Iek7Ymvqi0Cvt-lD9KibV8v1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage,
    detectSessionInUrl: false, // Disable session detection in URL to avoid redirection issues
  }
});
